language: cpp
os:
- linux
- osx
branches:
  only:
  - "/^v[0-9]/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  global:
  - DEBUG_CORE_DUMP="true"
  matrix:
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD="true"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  fast_finish: true
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.nvm
before_install:
- ulimit -c unlimited -S
- PACKAGER_URL="https://meshblu-connector.octoblu.com/tools/packager/latest"
- curl -fsS "${PACKAGER_URL}/travis_install_node.sh" -o /tmp/travis_install_node.sh
- chmod +x /tmp/travis_install_node.sh
- ". /tmp/travis_install_node.sh"
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH="true"; fi
- npm install --global yarn
install:
- yarn install
script:
- yarn test
after_success:
- yarn install --production
- yarn global add meshblu-connector-packager
- yarn run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
before_deploy:
- yarn install --production
- yarn run generate:package
- yarn run generate:schema
- cp schemas.json deploy
deploy:
- provider: releases
  api_key:
    secure: "EeKjyAKx5toRtVyKdqTG2GgEJ8r4Vb7VziWqtO75AcR/OZEVv0aJpQB0EM0duxZGkkoMi0B5qkvvIC33HkqiH96G/evFRSs7Qt8ZD5zIQjmKX4JgeMPI3gfZNqcwh8hBU27HGPum8e5KD0dWHhxlnrGI7d/xJKyOpq2D+8AStPnqakI1MuOsi9tPgZ5nGYdOg4l/9L3CIDOpNXfQzA+whvNUWW6FybAA/KuAGhux5XPWswvjTEKNgw475Fhq1d/Wu+xQcdOK1udAGUmN2fVjLWs4+iu04p7H0D6V7BLym3kTa/MTa7vh9Hz/Q0X6jifAN9clMHSMdgD67WHZ8o1pO7hnSXJ8BatrgkMtVZ7znO+opRWNSs+KoRcFJNfJq+aZVnBhcrENOXo7y+FsGH5IehzKISQRqpWmkWSDjIjem0LN1yYQ+kgSP4pzj20kZwOXJfrYuXkOckAF6q2K6uuc0SYLew2YIR2dirZhPqOyvo65o/dDCPxpqkzMwlMlExMbCjiH7JYGBbfbGWeOnX5QJyhg3XKHAnc8tCVUD9HiZvbd6HBPCjENnfRwtF6FtATzRmhZuJ1hVlzo5/CbOfxGOkE3ox/MG4Fn/hzsZvc7gOCnKnv0yIUzS8tSyTyqeDfEDXm/IOe/luqG71wXfHxLoka1HM7VfTC2kuyYExD+VwI="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "2+SfmRnBbpF1wDkv1cgWLToWVcbNcM/9nUsgZDMJ7JsTUyf2O6g/BRjgJ0lPQvsA7cDiUaMV1L/JblaVwK4S5pkluB05XvdXMKehnB1M2plr8d53NPL3on5hyyy14bnEk8/GBurHGRiKPRCfHg8ixwLnDGc1RGfpYoQYGyileock/wCRE8KKabQQhXDzq15t1eEF9XJE+C1hHlj1XK89AzxCPJYLF+rxLkIH5R9bOn/+iUVAKmbp9Ipn+w6OzOwV4UTen6oYzpNNpG7MNNVyMGDkK3CkLYq7XGNdDNwixlm+cgqaYWAFgUA1MW4QdrReq6w6po45lADQrIgZw3BqDkuGFI/sSWxXUo4DMFcMLWmyFf0nfQ2mSlEOPTTHMpJK0Y0JyTlALlh1saoLsDxDPkyR1a15uArRmGNTE2E037O+ylGjBJLkzMdcAZ1vGSWJN250jIWMQHJ1u2yybtPde6Al/coRoaifwg23IIg3D9gZmPoUBX5bQSHmcN0N0HJezY+p1hOzAuo1gCbzbd79loAo4DNUP5VZzIvf2nMhF/nzrfyCy6TPHqMBhf7YSh1EZ86fXhqHo9y4lGAixnLOAy6g23rUj8KZxFPD4AJHmlclR7i8gdnHeqeknTtXofhZL5YMvbltW8m9jt2YuGFUovi9aho4iufG6WyxqVtcjo4="
  on:
    tags: true
    condition: "$NPM_PUBLISH = true"
